In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
%matplotlib inline

In [ ]:
data = pd.read_excel('Final_Mark_Dataset.xlsx',sheet_name='Sheet2')

### Data Info

In [ ]:
data.head()

CGPA1  CGPA2  CGPA3  CGPA4  CGPA5  CGPA6  CGPA7  CGPA8  MATH  S1MATH  \
0   8.41   8.46  8.429  8.640  8.429  8.640  8.429  8.640    80      94   
1   7.64   8.07  7.953  8.136  7.953  8.136  7.953  8.136    97      97   
2   8.64   8.68  8.286  8.091  8.286  8.091  8.286  8.091    77      94   
3   8.91   8.88  8.762  8.955  8.762  8.955  8.762  8.955    75      92   
4   9.23   9.24  8.524  9.591  8.524  9.591  8.524  9.591    94      97   

   S2MATH  S3MATH  
0      79      78  
1      93      60  
2      86      62  
3      82      73  
4      88      67

In [ ]:
data.tail()

CGPA1  CGPA2  CGPA3  CGPA4  CGPA5  CGPA6  CGPA7  CGPA8  MATH  S1MATH  \
95  6.526   6.35  8.429   8.16  8.429   8.16  8.429   8.16    89      69   
96  6.526   6.35  6.095   6.90  6.095   6.90  6.095   6.90    80      62   
97  6.500   6.35  6.526   6.35  6.526   6.35  6.526   6.35    79      60   
98  4.500   7.10  7.571   6.98  7.571   6.98  7.571   6.98    75      54   
99  5.600   6.50  8.286   8.12  8.286   8.12  8.286   8.12    90      58   

    S2MATH  S3MATH  
95      55      85  
96      76      51  
97      56      65  
98      76      76  
99      67      86

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   CGPA1   100 non-null    float64
 1   CGPA2   100 non-null    float64
 2   CGPA3   100 non-null    float64
 3   CGPA4   100 non-null    float64
 4   CGPA5   100 non-null    float64
 5   CGPA6   100 non-null    float64
 6   CGPA7   100 non-null    float64
 7   CGPA8   100 non-null    float64
 8   MATH    100 non-null    int64  
 9   S1MATH  100 non-null    int64  
 10  S2MATH  100 non-null    int64  
 11  S3MATH  100 non-null    int64  
dtypes: float64(8), int64(4)
memory usage: 9.5 KB


In [ ]:
data.isnull()

CGPA1  CGPA2  CGPA3  CGPA4  CGPA5  CGPA6  CGPA7  CGPA8   MATH  S1MATH  \
0   False  False  False  False  False  False  False  False  False   False   
1   False  False  False  False  False  False  False  False  False   False   
2   False  False  False  False  False  False  False  False  False   False   
3   False  False  False  False  False  False  False  False  False   False   
4   False  False  False  False  False  False  False  False  False   False   
..    ...    ...    ...    ...    ...    ...    ...    ...    ...     ...   
95  False  False  False  False  False  False  False  False  False   False   
96  False  False  False  False  False  False  False  False  False   False   
97  False  False  False  False  False  False  False  False  False   False   
98  False  False  False  False  False  False  False  False  False   False   
99  False  False  False  False  False  False  False  False  False   False   

    S2MATH  S3MATH  
0    False   False  
1    False   False  
2    False   False  
3    False   False  
4    False   False  
..     ...     ...  
95   False   False  
96   False   False  
97   False   False  
98   False   False  
99   False   False  

[100 rows x 12 columns]

In [ ]:
data.describe()

CGPA1      CGPA2       CGPA3       CGPA4       CGPA5       CGPA6  \
count  100.000000  100.00000  100.000000  100.000000  100.000000  100.000000   
mean     8.094220    8.33706    8.060000    8.198200    8.060000    8.195800   
std      0.848137    0.69080    0.573983    0.730543    0.573983    0.730998   
min      4.500000    6.35000    6.095000    6.318000    6.095000    6.318000   
25%      7.680000    8.07000    7.762000    7.904250    7.762000    7.904250   
50%      8.180000    8.39000    8.071500    8.281500    8.071500    8.281500   
75%      8.662500    8.80000    8.440750    8.762500    8.440750    8.762500   
max      9.680000    9.76000    9.333000    9.591000    9.333000    9.591000   

            CGPA7       CGPA8        MATH      S1MATH      S2MATH      S3MATH  
count  100.000000  100.000000  100.000000  100.000000  100.000000  100.000000  
mean     8.060000    8.198800   84.030000   78.100000   82.070000   76.410000  
std      0.573983    0.730491    8.680007   13.555349    8.006632    9.491192  
min      6.095000    6.318000   70.000000   51.000000   55.000000   51.000000  
25%      7.762000    7.904250   77.000000   67.000000   78.000000   70.000000  
50%      8.071500    8.281500   83.000000   77.000000   83.000000   76.000000  
75%      8.440750    8.762500   91.250000   91.000000   87.000000   83.250000  
max      9.333000    9.591000   99.000000   99.000000   99.000000   99.000000

### Data Visualization

In [ ]:
# Creating the Figure instance
fig = px.line(x=data['CGPA1'], y=data['CGPA2']) 
  
# showing the plot
fig.show()

In [ ]:

fig = px.bar(data, x=data["CGPA1"], y=data["CGPA2"]) 
fig.show()

In [ ]:

fig = px.histogram(data, x="CGPA1", y="CGPA2") 
fig.show()

In [ ]:
fig = px.scatter(data, x="CGPA1", y="CGPA2") 
fig.show()

In [ ]:
fig = px.scatter_3d(data, x = 'CGPA1', 
                    y = 'CGPA2', 
                    z = 'CGPA3', 
                    color = 'CGPA8') 
  
fig.show()

### Model Building

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn import preprocessing,svm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [ ]:
X = data.drop(['CGPA4','CGPA5','CGPA6','CGPA7','CGPA8'], axis=1)

In [ ]:
X.head()

CGPA1  CGPA2  CGPA3  MATH  S1MATH  S2MATH  S3MATH
0   8.41   8.46  8.429    80      94      79      78
1   7.64   8.07  7.953    97      97      93      60
2   8.64   8.68  8.286    77      94      86      62
3   8.91   8.88  8.762    75      92      82      73
4   9.23   9.24  8.524    94      97      88      67

In [ ]:
y = data['CGPA8']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
print(r2_score(y_test, y_pred))

0.8066213839455596


In [ ]:
from sklearn.ensemble import RandomForestRegressor


In [ ]:
rf=RandomForestRegressor(oob_score=True)


In [ ]:
rf.fit(X_train, y_train)

RandomForestRegressor(oob_score=True)

In [ ]:
rf.oob_score_

0.7825154654400585

In [ ]:
rf.score(X_test, y_test)


0.8107614716388524

In [ ]:
from sklearn.svm import SVR

In [ ]:
svm=SVR()
svm.fit(X_train,y_train)

SVR()

In [ ]:
svr=svm.predict(X_test)

In [ ]:
resr1 = pd.DataFrame({'Actual': y_test, 'Predicted':svr})
resr1


Actual  Predicted
24   8.864   8.182937
47   9.150   8.715648
34   6.727   7.921741
85   8.760   8.556020
78   8.364   8.122027
95   8.160   8.127665
69   7.980   8.379191
37   7.636   8.489036
22   9.000   7.767642
92   7.909   8.032174
70   9.290   8.589713
17   9.000   8.724792
51   8.850   8.637595
23   7.455   7.869204
44   7.240   7.744237
38   7.500   7.918509
86   8.318   8.621504
87   8.760   8.506611
94   6.580   7.808172
3    8.955   8.383700

In [ ]:
svm.score(X_test, y_test)


0.3841039374588273

In [ ]:

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

from sklearn import preprocessing

import warnings

warnings.filterwarnings("ignore")

In [ ]:
gbc=GradientBoostingRegressor()

gbc.fit(X_train,y_train)

GradientBoostingRegressor()

In [ ]:
gbc.score(X_test,y_test)

0.8067503064983432

In [ ]:
from sklearn.preprocessing import PolynomialFeatures


In [ ]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_squared_error

In [ ]:
dr=DecisionTreeRegressor()
dr.fit(X_train,y_train)

DecisionTreeRegressor()

In [ ]:
dr.score(X_test,y_test)

0.7485242802437193

In [ ]:
y_pred=dr.predict(X_test)

In [ ]:
y_pred

array([8.864, 9.591, 6.98 , 8.76 , 7.74 , 8.62 , 7.98 , 7.864, 8.136,
       6.98 , 9.182, 9.   , 8.76 , 7.455, 8.   , 7.5  , 8.318, 8.76 ,
       6.318, 8.955])

In [ ]:
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
mse

0.15934974999999996

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

x_train_scaled = scaler.fit_transform(X_train)
x_train1 = pd.DataFrame(x_train_scaled)

x_test_scaled = scaler.fit_transform(X_test)
X_test1 = pd.DataFrame(x_test_scaled)

In [ ]:
from sklearn import neighbors
from sklearn.metrics import mean_squared_error 
from math import sqrt

In [ ]:
rmse_val = []
for K in range(10):
    K = K+1
    model = neighbors.KNeighborsRegressor(n_neighbors = K)

    model.fit(x_train1, y_train)  
    pred=model.predict(X_test1) 
    error = sqrt(mean_squared_error(y_test,pred)) 
    rmse_val.append(error) 
    print('RMSE value for k= ' , K , 'is:', error)

RMSE value for k=  1 is: 0.5871800831090921
RMSE value for k=  2 is: 0.6318937212854708
RMSE value for k=  3 is: 0.5305744475984918
RMSE value for k=  4 is: 0.5481636360385467
RMSE value for k=  5 is: 0.554084452046798
RMSE value for k=  6 is: 0.5714615266042757
RMSE value for k=  7 is: 0.5488747821959146
RMSE value for k=  8 is: 0.5348289073678141
RMSE value for k=  9 is: 0.5638325686159842
RMSE value for k=  10 is: 0.5466595494455391


In [ ]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [ ]:
for train_index, test_index in kf.split(X):
  print(train_index,test_index)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99] [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91
 92 93 94 95 96 97 98 99] [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25

In [ ]:
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=5)

In [ ]:
scores_l=[]
scores_svm=[]
scores_rf=[]
scores_dr=[]
scores_gb=[]
scores_knn=[]
for train_index,test_index in kf.split(data):
  X_train,X_test,y_train,y_test = X.iloc[train_index],X.iloc[test_index], y.iloc[train_index],y.iloc[test_index]
  scores_l.append(get_score(LinearRegression(),X_train,X_test,y_train,y_test))
  scores_svm.append(get_score(RandomForestRegressor(),X_train,X_test,y_train,y_test))
  scores_rf.append(get_score(SVR(),X_train,X_test,y_train,y_test))
  scores_dr.append(get_score(GradientBoostingRegressor(),X_train,X_test,y_train,y_test))
  scores_gb.append(get_score(DecisionTreeRegressor(),X_train,X_test,y_train,y_test))
  scores_knn.append(get_score(neighbors.KNeighborsRegressor(),X_train,X_test,y_train,y_test))

In [ ]:

print(scores_l)
print(np.mean(scores_l))

[0.6306178509018113, 0.7423495325212294, 0.77096279374487, 0.5576407341812728, 0.7256983269533723]
0.6854538476605112


In [ ]:

print(scores_rf)
print(np.mean(scores_rf))

[0.3054008954988736, 0.21593657914231057, 0.5987329537189505, -0.36663330673198335, 0.17476790095329764]
0.1856410045162898


In [ ]:
print(scores_svm)
print(np.mean(scores_svm))

[0.7459531168875589, 0.6572571761878034, 0.925425017288304, 0.7958082648136506, 0.8671521300112869]
0.7983191410377207


In [ ]:
print(scores_dr)
print(np.mean(scores_dr))

[0.7813290984490326, 0.7047249058512826, 0.9073605851776876, 0.82105020451734, 0.8069417757720783]
0.8042813139534843


In [ ]:
print(scores_gb)
print(np.mean(scores_gb))

[0.39752626597733376, 0.5200077225713595, 0.7343233591284848, 0.22400247820803432, 0.5665704877518516]
0.48848606272741274


In [ ]:
print(scores_knn)
print(np.mean(scores_knn))

[0.28010348424410114, 0.06976523392238032, 0.06476751768871647, -0.24362446253795111, 0.1606884818916794]
0.06634005104178524


In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
lrmean=cross_val_score(LinearRegression(),X,y,)
print(np.mean(lrmean))

cross_val_score(LinearRegression(),X,y)

0.6854538476605112


array([0.63061785, 0.74234953, 0.77096279, 0.55764073, 0.72569833])

In [ ]:
rfmean=cross_val_score(RandomForestRegressor(n_estimators=100),X,y)
print(np.mean(rfmean))
cross_val_score(RandomForestRegressor(),X,y)

0.7931858683513363


array([0.73617589, 0.66475114, 0.90451036, 0.81628446, 0.86660634])

In [ ]:
svrmean=cross_val_score(SVR(),X,y)
print(np.mean(svrmean))
cross_val_score(SVR(),X,y)

0.1856410045162898


array([ 0.3054009 ,  0.21593658,  0.59873295, -0.36663331,  0.1747679 ])

In [ ]:
gbrmean=cross_val_score(GradientBoostingRegressor(),X,y)
print(np.mean(gbrmean))
cross_val_score(GradientBoostingRegressor(),X,y)

0.8054708275946245


array([0.78046702, 0.6997558 , 0.90221673, 0.80937481, 0.81400887])

In [ ]:
dtrmean=cross_val_score(DecisionTreeRegressor(),X,y)
print(np.mean(dtrmean))
cross_val_score(DecisionTreeRegressor(),X,y)

0.5447158872198645


array([0.42173744, 0.47476601, 0.64117589, 0.46239824, 0.64044932])

In [ ]:
knnmean=cross_val_score(neighbors.KNeighborsRegressor(),X,y)
print(np.mean(knnmean))
cross_val_score(neighbors.KNeighborsRegressor(),X,y)

0.06634005104178524


array([ 0.28010348,  0.06976523,  0.06476752, -0.24362446,  0.16068848])

In [ ]:
from xgboost import XGBRegressor
xgmean=cross_val_score(XGBRegressor(),X,y)
print(np.mean(xgmean))
cross_val_score(XGBRegressor(),X,y)

0.7336262556695006


array([0.63212016, 0.59721903, 0.81396111, 0.69998853, 0.92484245])

In [ ]:
from sklearn.ensemble import RandomForestRegressor
zr = RandomForestRegressor(n_estimators=900, random_state=10)

In [ ]:
zr.fit(X_train, y_train)

RandomForestRegressor(n_estimators=900, random_state=10)

In [ ]:
ypr = zr.predict(X_test)

In [ ]:
resr = pd.DataFrame({'Actual': y_test, 'Predicted':ypr})
resr

Actual  Predicted
80   9.000   8.944390
81   6.318   7.189978
82   7.500   7.655717
83   8.318   8.238240
84   8.000   7.699590
85   8.760   8.825729
86   8.318   8.387544
87   8.760   8.826937
88   8.318   8.334071
89   7.890   7.995866
90   7.455   7.121560
91   8.864   8.545987
92   7.909   7.901728
93   8.273   8.484897
94   6.580   6.972612
95   8.160   8.260722
96   6.900   7.010430
97   6.350   6.909972
98   6.980   7.354916
99   8.120   8.167969

In [ ]:
from xgboost import XGBRegressor
zx = XGBRegressor(n_estimators=900, learning_rate=0.09)
zx.fit(X_train, y_train, 
       early_stopping_rounds=5,
       eval_set=[(X_test, y_test)],
       verbose=False)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.09, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             n_estimators=900, n_jobs=None, num_parallel_tree=None,
             predictor=None, random_state=None, ...)

In [ ]:
ypx = zx.predict(X_test)
from sklearn.metrics import r2_score as r2
print(r2(y_test,ypx))

0.9342725412400206


In [ ]:

resr2 = pd.DataFrame({'Actual': y_test, 'Predicted':ypx})
resr2

Actual  Predicted
80   9.000   9.098702
81   6.318   6.589551
82   7.500   7.530366
83   8.318   8.237109
84   8.000   7.819398
85   8.760   8.873112
86   8.318   8.382278
87   8.760   8.792949
88   8.318   8.344391
89   7.890   7.921374
90   7.455   7.331224
91   8.864   8.747200
92   7.909   7.792363
93   8.273   8.379671
94   6.580   6.777481
95   8.160   8.101546
96   6.900   6.918166
97   6.350   6.839432
98   6.980   7.257193
99   8.120   7.562979

In [ ]:
X_test.head()

CGPA1  CGPA2  CGPA3  MATH  S1MATH  S2MATH  S3MATH
80   8.91   9.00  9.333    97      97      86      96
81   7.59   8.02  7.143    89      72      86      79
82   7.82   8.07  7.810    82      78      76      67
83   7.95   8.20  8.048    90      62      78      80
84   7.68   7.90  7.619    98      57      80      79

In [ ]:
y_test.head()

80    9.000
81    6.318
82    7.500
83    8.318
84    8.000
Name: CGPA8, dtype: float64

In [ ]:
zr.predict([[7.59,8.02,7.143,89,72,86,79]])[0]

7.189977777777806

In [ ]:
l = []
for i in range(7):
  t = float(input())
  l.append(t)

zr.predict([l])[0]

7.59
8.02
7.143
89
72
86
79


7.189977777777806

In [ ]:
de= pd.read_excel('Final_Mark_Dataset.xlsx')


In [ ]:
x1test=pd.read_excel('Final_Mark_Dataset.xlsx',sheet_name='Sheet3')

In [ ]:
x1test

CGPA1  CGPA2  CGPA3  MATH  S1MATH  S2MATH  S3MATH
0    8.11   7.68   7.11    73      94      79      78
1    6.48   5.90   4.15    97      97      93      99
2    8.41   8.24   7.52    86      94      85      81
3    7.33   6.33   6.79    78      92      89      83
4    7.89   7.34   7.22    79      99      89      80
5    7.33   6.48   6.50    81      70      78      78
6    7.15   6.72   6.89    95      70      86      82
7    6.74   4.93   5.64    98      91      76      76
8    7.89   7.45   6.96    76      92      75      75
9    7.30   6.34   6.61    70      79      82      81
10   7.48   7.55   7.67    81      95      81      89
11   6.41   6.59   7.11    95      71      82      86
12   6.30   6.28   5.89    71      51      78      78
13   7.04   6.81   7.00    78      70      65      65
14   6.70   6.81   6.52    73      93      79      79
15   8.50   8.40   8.30    72      76      74      74
16   8.80   9.10   8.90    85      96      83      80
17   7.50   7.44   7.22    81      98      88      83
18   8.36   8.59   8.48    76      78      83      81
19   6.50   6.80   6.90    75      90      80      87

In [ ]:
y1test=pd.read_excel('Final_Mark_Dataset.xlsx',sheet_name='Sheet4')

In [ ]:
y1test

CGPA4
0    8.18
1    4.96
2    7.75
3    6.89
4    7.46
5    7.39
6    7.64
7    6.75
8    8.00
9    6.18
10   8.65
11   7.38
12   6.50
13   6.92
14   7.00
15   8.40
16   9.00
17   7.60
18   8.60
19   7.00

In [ ]:
ypr1=zr.predict(x1test)
ypr1

array([7.04266556, 7.07365333, 7.98491333, 6.84254778, 7.19808778,
       6.94611778, 7.05180333, 7.03531   , 7.05507556, 6.69315333,
       7.72306556, 7.01065222, 6.84282667, 6.84969111, 6.73519333,
       8.36426556, 8.95176444, 7.08090444, 8.69497333, 6.69118   ])

In [ ]:
df = pd.read_excel('Final_Mark_Dataset.xlsx')

In [ ]:
df.head()

Reg_No S11 S12 S13 S14 S15 S16 S17 S18 S19  ...  S73 S74 S75 S76 S77  \
0  20AD001   B  A+   A  A+  A+  B+   O   O   A  ...    A   A  A+   A  A+   
1  20AD002   B  A+   A   B  B+   A   A  A+  A+  ...    A   A  A+   A   A   
2  20AD003   O  A+  A+  B+  A   A+  B+   O   A  ...   A+   A  A+   A  A+   
3  20AD004   A  A+   O   O   A  A+  B+   O   A  ...    A  A+  A+  A+   O   
4  20AD005  A+   O   A   O  A+  A+  A+   O   A  ...   A+  A+  A+   A   O   

   CGPA7 S81 S82 S83  CGPA8  
0  8.429   O   A   A  8.640  
1  7.953   O   A  A+  8.136  
2  8.286   O   A  A+  8.091  
3  8.762   O   A  A+  8.955  
4  8.524   O  A+   O  9.591  

[5 rows x 74 columns]

In [ ]:
student = str(input())
ind = df.index[df['Reg_No']==student]
display(df.iloc[ind])


20ad002


Empty DataFrame
Columns: [Reg_No, S11, S12, S13, S14, S15, S16, S17, S18, S19, CGPA1, S21, S22, S23, S24, S25, S26, S27, S28, S29, CGPA2, S31, S32, S33, S34, S35, S36, S37, S38, S39, CGPA3, S41, S42, S43, S44, S45, S46, S47, S48, S49, S50, CGPA4, S51, S52, S53, S54, S55, S56, S57, S58, S59, CGPA5, S61, S62, S63, S64, S65, S66, S67, S68, S69, CGPA6, S71, S72, S73, S74, S75, S76, S77, CGPA7, S81, S82, S83, CGPA8]
Index: []

[0 rows x 74 columns]

In [ ]:
df=df.replace(to_replace="A+",value=9)
df=df.replace(to_replace="A",value=8)
df=df.replace(to_replace="B+",value=7)
df=df.replace(to_replace="B",value=6)
df=df.replace(to_replace="O",value=10)
df.head()

Reg_No  S11 S12 S13 S14 S15  S16 S17 S18 S19  ...  S73  S74 S75  S76 S77  \
0  20AD001    6   9   8   9   9    7  10  10   8  ...    8    8   9    8   9   
1  20AD002    6   9   8   6   7    8   8   9   9  ...    8    8   9    8   8   
2  20AD003   10   9   9   7  A     9   7  10   8  ...    9    8   9    8   9   
3  20AD004    8   9  10  10   8    9   7  10   8  ...    8    9   9    9  10   
4  20AD005    9  10   8  10   9    9   9  10   8  ...    9    9   9    8  10   

   CGPA7  S81  S82 S83  CGPA8  
0  8.429   10    8   8  8.640  
1  7.953   10    8   9  8.136  
2  8.286   10    8   9  8.091  
3  8.762   10    8   9  8.955  
4  8.524   10    9  10  9.591  

[5 rows x 74 columns]

In [ ]:
ml= df[['S24','S42','S33']]
ml.head()


S24  S42  S33
0   9    8    8
1  A     8    8
2   9    8    9
3   8    8    8
4  10    9    9

In [ ]:

student = str(input())
ind = df.index[df['Reg_No']==student]
row = (ml.iloc[ind])
display(row)



20AD002


S24  S42  S33
1  A     8    8

In [ ]:
import pickle
pickle_out = open("cgpa.pkl","wb")
pickle.dump(zr, pickle_out)
pickle_out.close()

In [240]:
zr = pickle.load(open('class.pkl', 'rb'))